### ISSUE TITLE
Using parent in slug adds tilde "~" in db  and in admin UI "/" so when fetching collection slug filed has parent-page~child-page

### ISSUE THREAD

**Issue by nikkizol** [mattmilburn/strapi-plugin-permalinks#33]
@mattmilburn I would expect to get parent-page/child-page instead of parent-page~child-page, is there a quick fix for this?

**Comment by mattmilburn** [comment]
Hi @nikkizol Currently that is intended behavior and it is due to the use of the `uid` field type which does not allow `/` characters. In the next major version of this plugin, **which is coming soon**, the custom permalink field will no longer be restricted by the limitations of the `uid` field and instead use a regular `text` field with some extra validation to keep things in order.

For the time being the quick fix is to simply use `str.replace('~', '/')` until an update is released for this plugin. Sorry for the trouble! I'll ping you on this issue once this is released 👍🏻

**Comment by mattmilburn** [comment]
Hi @nikkizol [Version 2.0.0](https://github.com/mattmilburn/strapi-plugin-permalinks/releases/tag/v2.0.0) of this plugin is now released and no longer uses the `~` character which should solve your issue. Please review the [migration guide](https://github.com/mattmilburn/strapi-plugin-permalinks/blob/main/MIGRATION.md) before upgrading 🙂
